using System;
/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * 
 * The idea behind is to calculate next number and then check if it is even and if it is smaller than 4000000.
 * If so add it to result else continue until the numbers exceed the 4000000 limit.
 */
namespace PEProblem002
{
    class Program
    {
        static void Main(string[] args)
        {
            DateTime StartTime = DateTime.Now;

            int f0 = 1;
            int f1 = 1;
            bool swich = true;
            bool whileContinue = true;
            int result = 0;

            while (whileContinue)
            {
                if (swich)
                {
                    f0 = f0 + f1;
                    swich = !swich;

                    if(f0 % 2 == 0)
                    {
                        if(f0 < 4000000)
                        {
                            result += f0;
                        }
                        else
                        {
                            whileContinue = false;
                        }
                    }
                }
                else
                {
                    f1 = f0 + f1;
                    swich = !swich;

                    if (f1 % 2 == 0)
                    {
                        if (f1 < 4000000)
                        {
                            result += f1;
                        }
                        else
                        {
                            whileContinue = false;
                        }
                    }
                }

            }

            TimeSpan elapsedTime = DateTime.Now - StartTime;

            Console.WriteLine("result: " + result.ToString());
            Console.WriteLine("elapsed time: " + elapsedTime.ToString("mm':'ss':'fff") + " mm:ss:fff");
            Console.ReadLine();
        }
    }
}
